name: Build AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
      
      - name: Create keystore
        run: echo "$KEYSTORE" | base64 -d > android/app/release.keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
      
      - name: Update build.gradle
        run: |
          sed -i 's|AziNews-release.keystore|release.keystore|g' android/app/build.gradle
      
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build AAB
        run: flutter build appbundle --release
      
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: azinews-aab
          path: build/app/outputs/bundle/release/app-release.aab
